version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: jondb
      POSTGRES_USER: jondb_user
      POSTGRES_PASSWORD: 2xyCmsk8tPHtbB4kgEtHkykem4S1g0Uw
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-net
    restart: unless-stopped

  api:
    build: .
    #這句的意思是 幫我從 .（也就是目前專案目錄）裡的 Dockerfile 建一個 image，並用這個 image 啟動 container。
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - app-net
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: jondb_user
      DB_PASSWORD: 2xyCmsk8tPHtbB4kgEtHkykem4S1g0Uw
      DB_NAME: jondb
      MY_HOST: localhost:8080
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  app-net:
